---
title: "Analyse factorielle des corespondances (AFC)"
author: "Axel-Cleris Gailloty"
date: "2023-03-03"
output: word_document
---

# Introduction

L'analyse des correspondances est une technique descriptive/exploratoire destinée à analyser des tables à double entrée ou plus contenant certaines mesures de correspondance entre les lignes et les colonnes. Les résultats donnent une information dont la nature est proche de celle fournie par les techniques d'Analyse Factorielle, et nous permettent d'explorer la structure des variables catégorielles de la table. Le type de table le plus courant est une table de fréquences à double entrée. 

Rechercher la meilleure représentation simultanée de deux ensembles constitutant les lignes et les colonnes d’une table de contingence.
Les lignes et les colonnes sont deux partitions des mêmes n individus. Elles jouent donc des rôles parfaitement symétriques.
On raisonne en terme de profils
⇓
Les modalités d’une même variable sont alors comparables entre elles.
Les proximités entre les points s’interprètent comme des similitudes.



# Sources 
Analyse des Correspondances. www.statsoft.fr. Accessed March 3, 2023. https://www.statsoft.fr/concepts-statistiques/analyse-des-correspondances/analyse-factorielle-des-correspondances.php
