project:
  type: website

website:
  title: "TD d'outils d'enquête, d'analyse de données et de décision"
  navbar:
    left:
      - index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



